# 1. THE PORT (Must be unique)
server.port=8083

# 2. RABBITMQ CONFIGURATION (To listen for the events)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# This matches the queue name we set in the property-service!
rabbitmq.notification.queue=myQueue

# 3. EMAIL CONFIGURATION (Required since you added spring-boot-starter-mail)
# You can put fake values here just to get the app to start,
# or use real Gmail SMTP credentials if you actually want to receive the emails.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fake_email@gmail.com
spring.mail.password=fake_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true