server.port=8081
# Notice the database name is changed to realestate_properties
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=realestate_properties;encrypt=true;trustServerCertificate=true;
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=update