server.port=8082
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=realestate_users;encrypt=true;trustServerCertificate=true;integratedSecurity=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update